spring:
  datasource:
    url: jdbc:postgresql://localhost:8081/postgresdb
    username: postgres
    password: postgres123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  flyway:
#    locations:
#      - classpath:db/migration
#      - classpath:db/migration-dev
