create table locales
(
    id      bigint generated by default as identity
        primary key,
    address varchar(255),
    lat     double precision not null,
    lng     double precision not null,
    name    varchar(255)
);


create table drinks
(
    id         bigint generated by default as identity
        primary key,
    brand_name varchar(255),
    category   varchar(255),
    price      double precision not null
);

create table users
(
    id                 bigserial primary key,
    email              varchar(255) unique,
    name               varchar(255),
    password           varchar(255),
    phone_number       varchar(255),
    role               varchar(255),
    works_in_locale_id bigint,

    constraint fk_locale foreign key (works_in_locale_id) references locales (id)

);

create table tables
(
    id        bigserial primary key,
    waiter_id bigint,
    constraint fk_waiter foreign key (waiter_id) references users (id)
);

create table orders
(
    id        bigserial not null primary key,
    opened_at timestamp not null,
    closed_at timestamp,
    table_id  bigint    not null,
    waiter_id bigint    not null,
    constraint fk_table foreign key (table_id) references tables (id),
    constraint fk_waiter foreign key (waiter_id) references users (id)

);

create table drinks_in_order
(
    id       bigserial primary key,
    drink_id bigint,
    order_id bigint,
    quantity integer not null,
    constraint fk_drink foreign key (drink_id) references drinks (id),
    constraint fk_order foreign key (order_id) references orders (id)
);

create table storage
(
    id        bigserial primary key,
    quantity  integer not null,
    drink_id  bigint,
    locale_id bigint,

    constraint fk_drink foreign key (drink_id) references drinks (id),
    constraint fk_locale foreign key (locale_id) references locales (id)
);







